// The single optional-LLM seam for the whole system.
//
// By DEFAULT this is fully offline: generative agents pass a set of curated,
// scenario-specific candidates (authored in /content) and `generate` deterministically
// selects/assembles one. No network, no API key, always works.
//
// To later route generation through a real model (e.g. Claude Opus 4.8), call
// `configureModelAdapter(fn)` once at startup with a function that calls your model.
// The app NEVER requires this — see README "Optional LLM adapter".

export type LLMSource = "curated-library" | "model";

export interface LLMRequest {
  task: string; // what we're generating, e.g. "onboarding-email"
  context: Record<string, unknown>; // data the agent just analyzed
  candidates: string[]; // curated options to choose from (offline default)
  seed?: number;
}

export interface LLMResponse {
  text: string;
  source: LLMSource;
  note: string;
}

type ModelAdapter = (req: LLMRequest) => Promise<string>;

let modelAdapter: ModelAdapter | null = null;

export function configureModelAdapter(fn: ModelAdapter | null): void {
  modelAdapter = fn;
}

export function hasModelAdapter(): boolean {
  return modelAdapter !== null;
}

// Stable string hash → deterministic, reproducible selection.
function djb2(str: string): number {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = (h * 33) ^ str.charCodeAt(i);
  return h >>> 0;
}

export const agentLLM = {
  async generate(req: LLMRequest): Promise<LLMResponse> {
    if (modelAdapter) {
      const text = await modelAdapter(req);
      return { text, source: "model", note: "Generated by the configured model adapter." };
    }
    if (req.candidates.length === 0) {
      return { text: "", source: "curated-library", note: "No candidates supplied." };
    }
    const idx = djb2(req.task + JSON.stringify(req.context) + (req.seed ?? 0)) % req.candidates.length;
    return {
      text: req.candidates[idx],
      source: "curated-library",
      note: "Selected from the curated, scenario-specific content library (offline default).",
    };
  },
};
